--- django/contrib/gis/gdal/libgdal.py	2018-09-19 20:38:48.632916748 +0200
+++ django/contrib/gis/gdal/libgdal.py	2018-09-19 22:15:15.676506466 +0200
@@ -2,6 +2,7 @@
 
 import logging
 import os
+import sys
 import re
 from ctypes import c_char_p, c_int, CDLL, CFUNCTYPE
 from ctypes.util import find_library
@@ -12,12 +13,12 @@
 logger = logging.getLogger('django.contrib.gis')
 
 # Custom library path set?
-try:
-    from django.conf import settings
-    lib_path = settings.GDAL_LIBRARY_PATH
-except (AttributeError, EnvironmentError,
-        ImportError, ImproperlyConfigured):
-    lib_path = None
+if 'linux' in sys.platform:
+    lib_path = os.path.join(sys.prefix, 'lib', 'libgdal.so')
+elif 'darwin' in sys.platform:
+    lib_path = os.path.join(sys.prefix, 'lib', 'libgdal.dylib')
+elif os.name == 'nt':
+    lib_path = os.path.join(sys.prefix, 'Library', 'bin', 'gdal201.dll')
 
 if lib_path:
     lib_names = None
